name: Azure Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:

  terraform-plan:
    runs-on: [self-hosted, Windows, X64]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init -input=false

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan


  approval:
    runs-on: [self-hosted, Windows, X64]
    needs: terraform-plan

    environment:
      name: dev

    steps:
    - run: echo "Waiting for approval..."


  terraform-apply:
    runs-on: [self-hosted, Windows, X64]
    needs: approval

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init -input=false

    - name: Terraform Apply
      run: terraform apply -auto-approve
